### ISSUE TITLE
what is hkd

### ISSUE THREAD

**Issue by bach-zouk** [cadurosar/graph_kd#1]
Hi,

Thank you for your code. I understand gkd and rkd in the code but not sure what does hkd refer to here? is this some baseline mentioned in your paper

**Comment by cadurosar** [comment]
Hi,

HKD refers to "Hinton" knowledge distillation, which was one of the first methods to introduce knowledge distillation (https://arxiv.org/abs/1503.02531). It is not used in the paper and it is on the codebase as an artifact of initial tests.
